### ISSUE TITLE
Allow the user to download the generated payload

### ISSUE THREAD

**Issue by agrare** [RedHatCloudForms/cfme-migration_analytics#19]
Come up with an alternate design for https://github.com/RedHatCloudForms/cfme-migration_analytics/pull/16

cc @himdel @martinpovolny

**Comment by himdel** [comment]
Maybe @skateman's idea about a separate static asset server would be relevant here..

**Comment by himdel** [comment]
(Though I still think accessing this kind of private data should be authenticated)

**Comment by skateman** [comment]
I vaguely remember something from the containerization effort about a static asset server. However, that doesn't provide us authentication.

**Comment by himdel** [comment]
I think we could still use the idea from https://github.com/RedHatCloudForms/cfme-migration_analytics/pull/16 , if we just add a proper authenticated API endpoint to server those files from the API appliance.

**Comment by skateman** [comment]
Yeah, not putting them into the `public` folder is a good start :wink:

**Comment by bthurber** [comment]
Per internal discussion:
- API will support download from the appliance the payload generation is run from
-  Multiple payloads can be generated on the same appliance however only the latest will be available for download when clicking the button
- API will provide path to file in task
- Generated payloads will reside in /tmp

**Comment by mturley** [comment]
@bthurber @agrare I was talking to @martinpovolny about this and he was asking how large we expect the payload file to be. Do you have an answer for that or know who we should talk to about it?

The question is whether the files will always be small enough to be downloaded via the API (at the range of megabytes or smaller). I seem to recall that we decided they will be, but I can't recall the actual sizes we expect.

**Comment by bthurber** [comment]
> @bthurber @agrare I was talking to @martinpovolny about this and he was asking how large we expect the payload file to be. Do you have an answer for that or know who we should talk to about it?
> 
> The question is whether the files will always be small enough to be downloaded via the API (at the range of megabytes or smaller). I seem to recall that we decided they will be, but I can't recall the actual sizes we expect.

That is correct.  A couple of MB would be the largest size expected.

**Comment by mturley** [comment]
Ah, looking at https://github.com/RedHatCloudForms/cfme-migration_analytics/pull/16#issuecomment-523790253 it seems a large payload is around 1MB

**Comment by martinpovolny** [comment]
Is there a way to know what is the file path to the latest payload?

What is supposed to be the input for the API call?

**Comment by mturley** [comment]
@martinpovolny the payload path is currently stored as `context_data.payload_path` on the MiqTask object that generated the payload. I imagined that the API call would take the task ID as its input, or maybe the task object could contain some other information the UI can use to identify what input to use for the download API call.

The task I'm referring to is created by the `bundle` action here: https://github.com/RedHatCloudForms/cfme-migration_analytics/blob/master/app/controllers/api/red_hat_migration_analytics_controller.rb#L13

To trigger this action, the UI makes a POST request at `/api/red_hat_migration_analytics` with the body `{ "action": "bundle", "provider_ids": [...] }` where `provider_ids` is an array of strings, the IDs of the CF providers to bundle data from. When the task completes, the UI uses `context_data.ip_address` and `context_data.payload_path` to display an SCP command the user can use. We just need to render a download button instead, and use data on the task to determine the API call it makes.

**Comment by martinpovolny** [comment]
Cool. Thx

So I'll implement an API function that, given a MiqTask ID will return the payload.
