### ISSUE TITLE
Allow a user to update manifest on a CF appliance

### ISSUE THREAD

**Issue by bthurber** [RedHatCloudForms/cfme-migration_analytics#27]
Use case:
  As a Migration Analytics user/admin, I would like the ability to update the manifest on my CF appliance through the UI.  This will provide the ability to enhance data collection used to generate the needed payload when analyzing my environment.  Required support:

- API:  import a new manifest
 - Check to see if a manifest exists and if so save the existing to a new file and import the new manifest

- UI:  provide an import/upload button where a file path can be selected for the new manifest file

**Comment by martinpovolny** [comment]
Progress:
I am trying to parse the API requirements from this task. The API issue that I asked for on our meeting was not created.

@mturley : You are the one who is going to use this API, aren't you?
For the upload, do you want classical multipart form data handling or will you pass the data as a string in a JSON body of a request?

**Comment by agrare** [comment]
> The API issue that I asked for on our meeting was not created.

Pretty sure this is that issue @martinpovolny :wink: What requirements are you missing?  Maybe I can help fill in any blanks

**Comment by martinpovolny** [comment]
@agrare : do you have an idea about the name of the endpoint?

something like `api/migration_analytics` and then an action such as `import`? Does that work for you, guys?

I remember there was also some talk about downloading the file. Shall I also add that or just the upload/import?
 
> Check to see if a manifest exists and if so save the existing to a new file and import the new manifest

Do you want to keep some history? Such as 10 files back named `name.1` `name.2' etc. and rotate on upload? Or just keep the latest and the original one (as someone said on a meeting that we had).

**Comment by agrare** [comment]
> do you have an idea about the name of the endpoint? Something like api/migration_analytics and then an action such as import? Does that work for you, guys?
>
> I remember there was also some talk about downloading the file. Shall I also add that or just the upload/import?

If we create a user_manifest or custom_manifest endpoint that we can GET/POST/DELETE that gives us some options but I don't feel strongly about the names of things.

The "custom" manifest just has to be stored at `/opt/rh/cfme-migration_analytics/manifest.json` if it is uploaded.

> Do you want to keep some history?

It would make the API a bit more complicated so unless there is a need we could just keep it simple, @bthurber ?

**Comment by mturley** [comment]
@martinpovolny 
> For the upload, do you want classical multipart form data handling or will you pass the data as a string in a JSON body of a request?

I was thinking JSON body of a request, but either way works for me, whatever is easiest for you. I don't expect the data to be very large, the [current default manifest](https://github.com/RedHatCloudForms/cfme-migration_analytics/blob/master/config/default-manifest.json) is ~8 KB.

As for keeping history, I'm not sure that's necessary, but we should definitely implement the DELETE method on that endpoint so the user can "restore default manifest" by deleting the custom one.

**Comment by martinpovolny** [comment]
> As for keeping history, I'm not sure that's necessary, but we should definitely implement the DELETE method on that endpoint so the user can "restore default manifest" by deleting the custom one. There's no need to remember an original file at this /opt/rh/... path, the app will default to the one stored in the gem if there is no custom file present.

As for the DELETE: the API is not ready to implement a DELETE w/o an ID

(cannot do `api delete red_hat_migration_analytics` would need something like `api delete red_hat_migration_analytics/1).

So I'd rather implement the resetting of the manifest using POST.

**Comment by mturley** [comment]
> I'd rather implement the resetting of the manifest using POST.

Sounds good to me 😄
